### ISSUE TITLE
Support for installing without SQLAlchemy dependency

### ISSUE THREAD

**Issue by mxsasha** [alex-oleshkevich/imia#10]
The package depends on SQLAlchemy 1.4+, but this is only used for specific user providers. I'd like to use it in a project that still needs SQLAlchemy 1.3, and am happy to write my own user providers. It would be great if the default install did not require SQLAlchemy at all, and move this to an extras_require option instead.

**Comment by alex-oleshkevich** [comment]
SA is a soft dependency of this package. See this line https://github.com/alex-oleshkevich/imia/blob/b55bb0eaf0dbf3a06fabe435460129fe9cb10482/pyproject.toml#L28

**Comment by alex-oleshkevich** [comment]
ok, i see the problem. let's see what i can do here.

**Comment by alex-oleshkevich** [comment]
@mxsasha fixed, thanks for the report.
