### ISSUE TITLE
Example for sqlalchemy core.

### ISSUE THREAD

**Issue by jeetu7** [alex-oleshkevich/imia#4]
I am trying to implement basic integration with imia-starlette-databases. The databases is using sqlalchemy-core/aiosqlite in the backend. I am at total loss about how to use imia with sqlite file persistence using the above libs. This might be due to my ignorance of protocols in python or me being new in async world. 

It would be nice if you can have one example in the examples dir with database persistence.

My current state:
[login_logout_databases_sqlite](https://gist.github.com/jeetu7/377e4bd7056cb222d9e114154ea345e6)

Thanks in advance

**Comment by jeetu7** [comment]
== .env ==
DATABASE_URL=sqlite:////tmp/test.db

**Comment by alex-oleshkevich** [comment]
Good point. I will add few more examples.
In the meantime, you need to create your own [UserProvider](https://github.com/alex-oleshkevich/imia/blob/master/docs/configuration.md#user-provider) to use sqlalchemy and databases. The purpose of user provides is to abstract the data storage from the library itself. So load user in it.

**Comment by jeetu7** [comment]
One working implementation is proposed in the PR #5
